
import FileManager.FileManager;
import javax.swing.JOptionPane;
import dataController.Controller;
import helper.Helper;
import java.io.IOException;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import java.time.Year;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this licensez
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sai Lin Htet
 */
public class Record extends javax.swing.JFrame {
    Helper helper=new Helper();
    String[] userInfo=new String[13];
    ArrayList<String> record = new ArrayList<>();

    /**
     * Creates new form NewJFrame
     */
    public Record(String[] userInfo,ArrayList<String> record ) {
        this.userInfo=userInfo.clone();
         this.record=record;
        

        initComponents();
        _resultList.setLayout(new BoxLayout(_resultList, BoxLayout.Y_AXIS));
        addComponents();
    }
private void addComponents(){
         _resultList.removeAll();
         System.out.println("Record.addComponents()"+this.record.size());
         try { 
             if(this.record.size() !=0 ){
                 for(int i=0;i<this.record.size();i++){ 
             List<String[]> userList = FileManager.getAllUser();
             List<String[]> user = Controller.findvalueFromArr(userList, "id", this.record.get(i),new Integer[]{}); 
             System.out.println("Home.<init>()"+ user.get(0)[1]); 
             JPanel userCard=helper.createCrad(user.get(0));
             _resultList.add(userCard);
             _resultList.revalidate();
             _resultList.repaint();
         }
             }else{
                 JPanel notfound=helper.createEmptyPanel();
                _resultList.add(notfound);
                _resultList.revalidate();
                _resultList.repaint();
             }
             
              }
         catch (Exception e) { 
             System.out.println(e.getMessage());
         JPanel notfound=helper.createEmptyPanel();
                _resultList.add(notfound);
                _resultList.revalidate();
                _resultList.repaint();}
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _GenderGp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        _home = new javax.swing.JButton();
        _profile = new javax.swing.JButton();
        _result = new javax.swing.JLabel();
        _ListScroll = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        _resultList = new javax.swing.JPanel();
        _profile1 = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        _home.setText("Home");
        _home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _homeActionPerformed(evt);
            }
        });

        _profile.setText("Profile");
        _profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _profileActionPerformed(evt);
            }
        });

        _result.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _result.setText("History(" +
            (!this.record.isEmpty() && this.record.get(0).charAt(0) != '\0'
                ? this.record.size()
                : 0)
            + ")");

        _resultList.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout _resultListLayout = new javax.swing.GroupLayout(_resultList);
        _resultList.setLayout(_resultListLayout);
        _resultListLayout.setHorizontalGroup(
            _resultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        _resultListLayout.setVerticalGroup(
            _resultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(_resultList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_resultList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        _ListScroll.setViewportView(jPanel3);

        _profile1.setText("Record");
        _profile1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _profile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _profile1ActionPerformed(evt);
            }
        });

        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_home)
                    .addComponent(_profile)
                    .addComponent(_profile1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_ListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(_result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clearbtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_home)
                    .addComponent(_result)
                    .addComponent(Clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(_profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_profile1)
                        .addContainerGap(473, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(_ListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__profileActionPerformed
        // TODO add your handling code here:
        Profile profile=new Profile(this.userInfo,this.record);
        setVisible(false);
        profile.setVisible(true);
    }//GEN-LAST:event__profileActionPerformed

    private void _profile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__profile1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event__profile1ActionPerformed

    private void _homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__homeActionPerformed
        // TODO add your handling code here:
        Home home=new Home(this.userInfo,this.record);
        setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event__homeActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        try {
            FileManager.updateRecord(new String[]{this.userInfo[12],""});
            _resultList.removeAll();
            this.record=new ArrayList<>();
            JPanel notfound=helper.createEmptyPanel();
                _resultList.add(notfound);
                _resultList.revalidate();
                _resultList.repaint();
            
        } catch (Exception e) {
            System.exit(1);
        }
        
    }//GEN-LAST:event_ClearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearbtn;
    private javax.swing.ButtonGroup _GenderGp;
    private javax.swing.JScrollPane _ListScroll;
    private javax.swing.JButton _home;
    private javax.swing.JButton _profile;
    private javax.swing.JButton _profile1;
    private javax.swing.JLabel _result;
    private javax.swing.JPanel _resultList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
