/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week3;

/**
 *
 * @author Sai Lin Htet
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        InputNum1Field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputNum2Field = new javax.swing.JTextField();
        OutField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CalculateBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        Plus_radio = new javax.swing.JRadioButton();
        Nav_radio = new javax.swing.JRadioButton();
        Into_radio = new javax.swing.JRadioButton();
        Black_radio = new javax.swing.JRadioButton();
        Power_radio = new javax.swing.JRadioButton();
        Persent_radio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Num1");

        InputNum1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNum1FieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Num2");

        jLabel2.setText("operator");

        OutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Out");

        CalculateBtn.setText("Calculate");
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(Plus_radio);
        Plus_radio.setText("+");
        Plus_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Nav_radio);
        Nav_radio.setText("-");
        Nav_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nav_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Into_radio);
        Into_radio.setText("*");

        buttonGroup1.add(Black_radio);
        Black_radio.setText("/");

        buttonGroup1.add(Power_radio);
        Power_radio.setText("^");
        Power_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Power_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Persent_radio);
        Persent_radio.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputNum1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(InputNum2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OutField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(Persent_radio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Power_radio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Plus_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nav_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Into_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Black_radio)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CalculateBtn)
                .addGap(18, 18, 18)
                .addComponent(ClearBtn)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputNum1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Plus_radio)
                    .addComponent(Nav_radio)
                    .addComponent(Into_radio)
                    .addComponent(Black_radio)
                    .addComponent(Power_radio)
                    .addComponent(Persent_radio))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(InputNum2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn)
                    .addComponent(CalculateBtn))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNum1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNum1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNum1FieldActionPerformed

    private void OutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutFieldActionPerformed

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
        // TODO add your handling code here:
       int num1=Integer.parseInt(InputNum1Field.getText());
        String operator="";
        int num2=Integer.parseInt(InputNum2Field.getText());
        float ans=0;
        if(Plus_radio.isSelected()){
            operator="+";
        }else if(Nav_radio.isSelected()){
            operator="-";
        }else if(Into_radio.isSelected()){
            operator="*";
        }else if(Black_radio.isSelected()){
            operator="/";
        }else if(Persent_radio.isSelected()){
            operator="%";
        }else if(Power_radio.isSelected()){
            operator="^";
        }
        
        switch (operator) {
            case "+":
                ans = num1+num2;
                break;
            case "-":
                ans = num1-num2;
                break;
            case "*":
                ans = num1*num2;
                break;
            case "/":
                ans = num1/num2;
                break;
            case "%":
                ans = num1%num2;
                break; 
            case "^":
                ans = Math.powExact(num1, num2);
                break;    
            default:
                throw new AssertionError();
        }
        OutField.setText(ans+"");
    }//GEN-LAST:event_CalculateBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
       InputNum1Field.setText("");
       
       InputNum2Field.setText("");
       
InputNum1Field.requestFocus();

    }//GEN-LAST:event_ClearBtnActionPerformed

    private void Plus_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plus_radioActionPerformed

    private void Nav_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nav_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nav_radioActionPerformed

    private void Power_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Power_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Power_radioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Black_radio;
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField InputNum1Field;
    private javax.swing.JTextField InputNum2Field;
    private javax.swing.JRadioButton Into_radio;
    private javax.swing.JRadioButton Nav_radio;
    private javax.swing.JTextField OutField;
    private javax.swing.JRadioButton Persent_radio;
    private javax.swing.JRadioButton Plus_radio;
    private javax.swing.JRadioButton Power_radio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
